"""Add email and hashed_password to users

Revision ID: 565db3ab855f
Revises: e60027802bd9
Create Date: 2026-02-22 01:26:31.693495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '565db3ab855f'
down_revision: Union[str, None] = 'e60027802bd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.alter_column('business_domain',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('RETAIL', 'FINANCE', 'TECHNOLOGY', 'HEALTHCARE', 'OTHER', 'FIRST', 'SECOND', 'THIRD', name='businessdomain'),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_leads_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_phone'), ['phone'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('hashed_password', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_column('hashed_password')
        batch_op.drop_column('email')

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_phone'))
        batch_op.drop_index(batch_op.f('ix_leads_email'))
        batch_op.alter_column('business_domain',
               existing_type=sa.Enum('RETAIL', 'FINANCE', 'TECHNOLOGY', 'HEALTHCARE', 'OTHER', 'FIRST', 'SECOND', 'THIRD', name='businessdomain'),
               type_=sa.VARCHAR(length=6),
               existing_nullable=True)

    # ### end Alembic commands ###
