"""add_lead_history_table

Revision ID: 5dffa85f7f0e
Revises: 001_initial
Create Date: 2026-02-21 22:03:23.958855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dffa85f7f0e'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('full_name', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_leads', sa.Integer(), nullable=False),
    sa.Column('current_leads', sa.Integer(), nullable=False),
    sa.Column('domains', sa.String(length=512), nullable=True),
    sa.Column('leads_handled', sa.Integer(), nullable=False),
    sa.Column('sales_converted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_telegram_id'), ['telegram_id'], unique=True)

    op.create_table('lead_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('old_stage', sa.String(length=50), nullable=True),
    sa.Column('new_stage', sa.String(length=50), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_lead_history_lead_id_leads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_history'))
    )
    with op.batch_alter_table('lead_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_history_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_history_lead_id'), ['lead_id'], unique=False)

    op.create_table('lead_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.String(length=64), nullable=True),
    sa.Column('author_name', sa.String(length=128), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_lead_notes_lead_id_leads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_notes'))
    )
    with op.batch_alter_table('lead_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_notes_lead_id'), ['lead_id'], unique=False)

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_leads_assigned_to_id'), ['assigned_to_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_leads_assigned_to_id_users'), 'users', ['assigned_to_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_leads_assigned_to_id_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_leads_assigned_to_id'))
        batch_op.drop_column('assigned_to_id')

    with op.batch_alter_table('lead_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_notes_lead_id'))

    op.drop_table('lead_notes')
    with op.batch_alter_table('lead_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_history_lead_id'))
        batch_op.drop_index(batch_op.f('ix_lead_history_id'))

    op.drop_table('lead_history')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
