"""Add SUPER_ADMIN and AGENT to UserRole

Revision ID: 7c5e7fd87393
Revises: 5dffa85f7f0e
Create Date: 2026-02-21 22:17:31.563093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c5e7fd87393'
down_revision: Union[str, None] = '5dffa85f7f0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('SUPER_ADMIN', 'ADMIN', 'MANAGER', 'AGENT', name='userrole'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('SUPER_ADMIN', 'ADMIN', 'MANAGER', 'AGENT', name='userrole'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)

    # ### end Alembic commands ###
