"""add_lead_attachments

Revision ID: c6f2e13bf605
Revises: 7c5e7fd87393
Create Date: 2026-02-21 22:23:20.424368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6f2e13bf605'
down_revision: Union[str, None] = '7c5e7fd87393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
